server.port: ${PORT:8082}
spring:
  application.name: github-webhook
  cloud.stream.bindings.output:
    content-type: application/json
    destination: messages

management.endpoints.web.exposure.include: "*"
management.endpoints.web.base-path: /